# Generated by Django 5.1 on 2024-08-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('LeagueID', models.AutoField(primary_key=True, serialize=False)),
                ('LeagueName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=100)),
                ('BoxOfficeEarnings', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('leagues', models.ManyToManyField(related_name='users', to='league.league')),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.league')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.user')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='movies',
            field=models.ManyToManyField(through='league.UserMovieMap', to='league.movie'),
        ),
    ]
